apiVersion: v1
kind: Namespace
metadata:
  name: database

---

apiVersion: v1
kind: ResourceQuota
metadata: 
  name: database-rc
  namespace: database
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "1.5"
    limits.memory: 4Gi

---

apiVersion: v1
kind: Namespace
metadata:
  name: admin

---

apiVersion: v1
kind: ResourceQuota
metadata: 
  name: admin-rc
  namespace: admin
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "1.5"
    limits.memory: 4Gi

---

apiVersion: v1
kind: Namespace
metadata:
  name: user

---

apiVersion: v1
kind: ResourceQuota
metadata: 
  name: user-rc
  namespace: user
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "1.5"
    limits.memory: 4Gi
