apiVersion: v1
kind: Service
metadata:
  name: user-ui-svc
  namespace: user
spec:
  type: NodePort
  selector:
    app: user-ui
    module: user
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32000
