apiVersion: v1
kind: Service
metadata:
  name: admin-ui-svc
  namespace: admin
spec:
  type: NodePort
  selector:
    app: admin-ui
    module: admin
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32002
