apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
  namespace: database
spec:
  selector:
    matchLabels:
      app: mongo-db
  serviceName: mongo-db-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      nodeSelector:
        module: database
      containers:
      - name: mongo-db
        image: mongo
        ports:
        - containerPort: 27017
          name: dbport
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-db-secrets
                key: dbuser
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-db-secrets
                key: dbpass
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits: 
            memory: "8Gi"
            cpu: "1500m"
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
              - mongo
              - --eval
              - db.adminCommand('ping')
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 5