apiVersion: v1
kind: Service
metadata:
  name: admin-api-svc
  namespace: admin
spec:
  type: NodePort
  selector:
    app: admin-api
    module: admin
  ports:
  - port: 1025
    targetPort: 1025
    nodePort: 32003
